# Meta
description: Private theme for artifact.me
keywords: hexo,theme,artifact,otakism

# Author
author_avatar: https://avatars1.githubusercontent.com/u/1223020?s=400&u=c3a99ef61b76bff024adc28d0c884265fbea98a0&v=4

# Search
search: 
  enable: true
  service: hexo # swiftype/google/hexo/algolia/azure
  # google 
  google_api_key: 
  google_engine_id: 
  # algolia
  algolia_app_id: 
  algolia_api_key: 
  algolia_index_name: 
  # azure
  azure_service_name: 
  azure_index_name: 
  azure_query_key: 

# Miscellaneous
google_analytics: UA-74859643-1
favicon: /favicon.png

# Less
less:
  compress: true

# use url, not username
social:
- name: feed
  url: https://medium.com/feed/@deptno
- name: mail
  url: mailto:deptno@gmail.com
- name: github
  url: https://github.com/deptno
- name: twitter
  url: https://twitter.com/deptno
- name: google
  url: https://plus.google.com/u/0/+이봉균
- name: facebook
  url: https://www.facebook.com/bonggyun.lee.7
- name: linkedin
  url: https://www.linkedin.com/in/bonggyun-lee-b55359b3/
- name: weibo
  url: 
- name: tumblr
  url: 
- name: dribbble
  url: 
- name: pinterest
  url: 
- name: instagram
  url: https://www.instagram.com/deptno/
- name: behance
  url: 
- name: feed
  url: /atom.xml
